Add fromOption, fromIO and fromTask
gcanti/fp-ts-rxjs pull request #20
Opened 2020-01-28 13:30 UTC by mlegenhausen

2020-01-28 14:16 UTC, gcanti requested changes

2020-01-28 14:16 UTC, gcanti commented on src/Observable.ts
> +import * as IO from 'fp-ts/lib/IO'
we can import only the types here

```ts
import { IO } from 'fp-ts/lib/IO'
import { Task } from 'fp-ts/lib/Task'
```

2020-01-28 14:16 UTC, gcanti commented on src/Observable.ts
> +export function fromOption<A>(o: O.Option<A>): Observable<A> {
what about

```ts
export function fromOption<A>(o: O.Option<A>): Observable<A> {
  return O.isNone(o) ? EMPTY : of(o.value)
}
```

2020-01-28 14:28 UTC, gcanti approved these changes

2020-01-28 14:29 UTC, merged

2020-01-28 14:29 UTC, gcanti commented
Thanks @mlegenhausen

2021-01-12 01:10 UTC, anthonyjoeseph commented
@mlegenhausen Just out of curiosity, is there a reason `fromIO` uses asynchronous context?

For example, it could have been implemented like so:

```ts
export function fromIO<A>(io: IO<A>): Observable<A> {
  return defer(() => rxOf(io()))
}
```

Is there an advantage to using `async` here instead? Is it conceptually more correct?

2021-01-12 07:01 UTC, mlegenhausen commented
> Is there an advantage to using async here instead? Is it conceptually more correct?

Don't think so. I think I chose `async` cause it was more inline with the `fromTask` implementation. Without knowing the internals (and the rxjs documentation isn't there of any help) it could be that your implementation could save one event loop iteration when calling the `IO` but this is only a guess.

2021-01-13 23:10 UTC, anthonyjoeseph commented
I think you're right. `fromIO` wasn't working for my [game engine](https://github.com/anthonyjoeseph/game-ts/blob/master/test/Render.test.ts) b/c [TestScheduler doesn't work in async contexts](https://github.com/ReactiveX/rxjs/pull/745), but when I rolled my own [fromSyncIO](https://github.com/anthonyjoeseph/game-ts/blob/master/src/util.ts) it worked just fine.

Could this be a desired PR? It does seem mildly more correct since you can raise into asynchronous context with [observeOn(AsyncScheduler)](https://rxjs-dev.firebaseapp.com/api/operators/observeOn#example) but you can't go back to synchronous context from async.

 It probably doesn't matter most use cases though, especially since the function is so simple, and I certainly don't mind using my own `fromSyncIO` in that case.

2021-01-14 10:23 UTC, mlegenhausen commented
> Could this be a desired PR?

Yes definitely.

2021-01-14 20:59 UTC, anthonyjoeseph commented
[PR](https://github.com/gcanti/fp-ts-rxjs/pull/43)