Alternative and Filterable to ReaderObservable added
gcanti/fp-ts-rxjs pull request #23
Opened 2020-02-17 15:37 UTC by mlegenhausen

2020-02-18 18:01 UTC, gcanti requested changes

2020-02-18 18:01 UTC, gcanti commented on src/ReaderObservable.ts
> +  alt: (fx, f) => r => merge(fx(r), f()(r)),
I'd reuse the `R.observable` instance here

```ts
alt: (fx, f) => r => R.observable.alt(fx(r), () => f()(r))
```

2020-02-18 18:01 UTC, gcanti commented on src/ReaderObservable.ts
> +  filterMap: <R, A, B>(fa: ReaderObservable<R, A>, f: (a: A) => O.Option<B>) => (r: R) =>
Nitpick: no need for type annotations here

```ts
filterMap: (fa, f) => r => R.observable.filterMap(fa(r), f)
```

2020-02-19 07:14 UTC, gcanti requested changes

2020-02-19 07:14 UTC, gcanti commented on docs/modules/Observable.ts.md
> -- [toTask](#totask)
oh, looks like you have a old version of `docs-ts` installed, could you please install `docs-ts@latest` and generate the docs again?

2020-02-19 07:14 UTC, gcanti commented on docs/modules/Observable.ts.md
> -- [toTask](#totask)
current version in `package.json` is `0.3.4`

2020-02-19 07:28 UTC, mlegenhausen commented
Looks better now. I also fixed a few wrong `since` comments.

2020-02-19 07:40 UTC, gcanti approved these changes

2020-02-19 07:41 UTC, merged

2020-02-19 07:57 UTC, gcanti commented
Thanks @mlegenhausen, released.